### ISSUE TITLE
Switch fireactions_url to GitHub Release

### ISSUE THREAD

**Issue by SchoolGuy** [hostinger/ansible-collection-fireactions#28]
Hey there,

I just wanted to remind you about the TODO @konradasb .

The following worked for me in the Ansible Playbook:

```yaml
fireactions_version: 0.3.0
fireactions_url: |
        https://github.com/hostinger/fireactions/releases/download/v{{ fireactions_version }}/fireactions-v{{ fireactions_version }}-linux-{{ fireactions_arch }}.tar.gz
```

Do you want a PR? The README talks of a `CONTRIBUTING.md`, but this is not present in this repo atm, so I am not sure what the rules are.
